### ISSUE TITLE
How to reference dependency outputs from parent bundle action?

### ISSUE THREAD

**Issue by carolynvs** [getporter/proposals#18]
Do we want to continue to allow bundle actions to use `${bundle.dependencies.DEP.outputs.OUTPUT_NAME}`?

Now that dependencies can promote outputs to the parent bundle, (below), do we need to change how we allow the parent bundle to reference dependency outputs?

```yaml
dependencies
  requires:
  - name: mysql
    outputs:
      connstr: "
Server=${bundle.parameters.host};Database=${outputs.db};Uid=${outputs.uid};Pwd=${outputs.pwd}"

install:
- exec:
    command: ./install.sh
    arguments:
    - ${bundle.dependencies.mysql.outputs.connstr} # what value should this hold???
    - ${outputs.connstr} # uses the concatenated value created in the dependency definition
```

What's not clear is what `bundle.dependencies.mysql.outputs.connstr` should reference. A dependency can generate an output, map it to another value and make it available to the parent bundle. So I can see users being confused if that variable contains the original value or the mapped value.

If we remove that template variable from the actions, that is a breaking change to dependencies.

We could keep it and have it refer to the value "closest in scope".
- If the dependency generates connstr, and doesn't provide a mapping, we use that original value.
- If an output mapping named connstr is delcared, we use that.
- If a bundle generates connstr, and defines a mapping, we use the mapped value.
- If a mixin also generates an output named connstr, `bundle.dependencies.mysql.outputs.constr` would not be updated but `bundle.outputs.connstr` would.

**Comment by kichristensen** [comment]
I think the cleanest long-term solution here is to restrict `bundle.dependencies.DEP.outputs.NAME` to the `dependencies.requires[]` wiring block only (mapping/promotion), and require action steps (install/upgrade/etc.) to reference dependency data exclusively via `bundle.outputs.NAME` after explicit promotion.

Rationale:
- One lookup path for actions - no ambiguity about raw vs mapped values.
- Easy to validate: `bundle.dependencies.*` used outside `requires[]` is a schema/lint error.
- Avoids "action at a distance" semantics where changing a mapping elsewhere silently changes what an existing template reference resolves to.

Tradeoff: this is a breaking change against the current draft. The `dbCon` examples in the doc reference `bundle.dependencies.sqlserver.outputs.dbCon` directly inside `install.exec.arguments`, with no promotion step. To land this cleanly we'd need:
- A lint/validation rule scoped to dependencies v2 that flags `bundle.dependencies.*` used outside the `requires[]` wiring block, with a clear error message pointing at the fix.
- Doc/example updates showing the promotion step, e.g.:

```yaml
dependencies:
  requires:
    - name: sqlserver
      bundle:
        reference: azure/sqlserver:v1.2.68
        interface:
          outputs:
            - name: dbCon
              $id: "azure-sql-server-connection-string"
      outputs:
        dbCon: ${ outputs.dbCon }   # explicit promotion

install:
- exec:
    arguments:
    - ${ bundle.outputs.dbCon }   # actions only ever read bundle.outputs
```

Happy to update the PEP003 examples and open a follow-up for the lint rule if this direction sounds right.
